export const adminStyles = {
  page: {
    fontFamily: "'Tajawal', system-ui, sans-serif",
    padding: '32px 36px',
    color: '#e2e8f0',
    minHeight: '100vh',
  },
  headerBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '2px solid rgba(212, 175, 55, 0.3)',
    paddingBottom: 20,
    marginBottom: 28,
  },
  title: {
    fontSize: 28,
    fontWeight: 900,
    marginBottom: 4,
    color: '#f8fafc',
  },
  subtitle: {
    fontSize: 15,
    color: '#94a3b8',
    marginBottom: 24,
  },
  formCard: {
    background: 'rgba(30, 41, 59, 0.6)',
    border: '1px solid rgba(212, 175, 55, 0.25)',
    borderRadius: 16,
    padding: 32,
    backdropFilter: 'blur(10px)',
    maxWidth: 640,
  },
  label: {
    display: 'block',
    marginTop: 20,
    fontSize: 16,
    fontWeight: 700,
    color: '#cbd5e1',
  },
  input: {
    width: '100%',
    padding: '14px 16px',
    marginTop: 8,
    fontSize: 16,
    fontFamily: "'Tajawal', system-ui, sans-serif",
    border: '1px solid rgba(148, 163, 184, 0.3)',
    borderRadius: 10,
    background: 'rgba(15, 23, 42, 0.5)',
    color: '#f1f5f9',
    boxSizing: 'border-box' as const,
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 16,
    marginBottom: 10,
    padding: '10px 12px',
    background: 'rgba(15, 23, 42, 0.4)',
    borderRadius: 8,
    color: '#e2e8f0',
  },
  checkbox: {
    width: 20,
    height: 20,
    accentColor: '#d4af37',
  },
  button: {
    width: '100%',
    padding: '16px',
    marginTop: 28,
    fontSize: 17,
    fontWeight: 700,
    fontFamily: "'Tajawal', system-ui, sans-serif",
    background: '#d4af37',
    color: '#0f172a',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
  },
  error: {
    color: '#fca5a5',
    marginTop: 14,
    fontSize: 15,
    background: 'rgba(239, 68, 68, 0.1)',
    padding: '10px 14px',
    borderRadius: 8,
  },
  statCard: {
    flex: 1,
    background: 'rgba(30, 41, 59, 0.6)',
    borderRadius: 16,
    padding: 24,
    border: '1px solid rgba(212, 175, 55, 0.25)',
    backdropFilter: 'blur(10px)',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 6,
  },
  statValue: {
    color: '#d4af37',
    fontSize: 32,
    fontWeight: 900,
  },
  actionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: 16,
    marginTop: 20,
  },
  actionCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '22px 16px',
    background: 'rgba(30, 41, 59, 0.6)',
    color: '#f1f5f9',
    borderRadius: 14,
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: 14,
    border: '1px solid rgba(212, 175, 55, 0.25)',
    textAlign: 'center' as const,
  },
  chartCard: {
    background: 'rgba(30, 41, 59, 0.6)',
    border: '1px solid rgba(212, 175, 55, 0.25)',
    borderRadius: 16,
    padding: 24,
    backdropFilter: 'blur(10px)',
  },
}