export const adminStyles = {
  page: {
    maxWidth: 640,
    margin: '40px auto',
    fontFamily: 'system-ui, sans-serif',
    padding: 32,
    background: '#fff',
    color: '#111',
    borderRadius: 16,
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#666',
    marginBottom: 24,
  },
  label: {
    display: 'block',
    marginTop: 20,
    fontSize: 16,
    fontWeight: 600,
    color: '#222',
  },
  input: {
    width: '100%',
    padding: '14px 16px',
    marginTop: 8,
    fontSize: 16,
    border: '1px solid #ddd',
    borderRadius: 10,
    boxSizing: 'border-box' as const,
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 16,
    marginBottom: 10,
    padding: '10px 12px',
    background: '#f8f8f8',
    borderRadius: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
  },
  button: {
    width: '100%',
    padding: '16px',
    marginTop: 28,
    fontSize: 17,
    fontWeight: 700,
    background: '#111',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
  },
  error: {
    color: '#d32f2f',
    marginTop: 14,
    fontSize: 15,
    background: '#fdecea',
    padding: '10px 14px',
    borderRadius: 8,
  },
}