export const adminStyles = {
  page: {
    maxWidth: 1100,
    margin: '0 auto',
    fontFamily: "'Tajawal', system-ui, sans-serif",
    padding: '40px 32px',
    background: '#ffffff',
    color: '#0f172a',
  },
  headerBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '3px solid #d4af37',
    paddingBottom: 20,
    marginBottom: 28,
  },
  title: {
    fontSize: 30,
    fontWeight: 900,
    marginBottom: 4,
    color: '#0f172a',
  },
  subtitle: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 24,
  },
  formCard: {
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: 16,
    padding: 32,
    boxShadow: '0 4px 20px rgba(15, 23, 42, 0.06)',
    maxWidth: 640,
  },
  label: {
    display: 'block',
    marginTop: 20,
    fontSize: 16,
    fontWeight: 700,
    color: '#334155',
  },
  input: {
    width: '100%',
    padding: '14px 16px',
    marginTop: 8,
    fontSize: 16,
    fontFamily: "'Tajawal', system-ui, sans-serif",
    border: '1px solid #cbd5e1',
    borderRadius: 10,
    background: '#f8fafc',
    boxSizing: 'border-box' as const,
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 16,
    marginBottom: 10,
    padding: '10px 12px',
    background: '#f1f5f9',
    borderRadius: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    accentColor: '#0f172a',
  },
  button: {
    width: '100%',
    padding: '16px',
    marginTop: 28,
    fontSize: 17,
    fontWeight: 700,
    fontFamily: "'Tajawal', system-ui, sans-serif",
    background: '#0f172a',
    color: '#d4af37',
    border: '2px solid #0f172a',
    borderRadius: 10,
    cursor: 'pointer',
  },
  error: {
    color: '#b91c1c',
    marginTop: 14,
    fontSize: 15,
    background: '#fef2f2',
    padding: '10px 14px',
    borderRadius: 8,
  },
  statCard: {
    flex: 1,
    background: '#0f172a',
    borderRadius: 16,
    padding: 24,
    border: '1px solid #0f172a',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 6,
  },
  statValue: {
    color: '#d4af37',
    fontSize: 32,
    fontWeight: 900,
  },
  actionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 16,
    marginTop: 28,
  },
  actionCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '26px 16px',
    background: '#0f172a',
    color: '#ffffff',
    borderRadius: 14,
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: 15,
    border: '2px solid #0f172a',
    textAlign: 'center' as const,
  },
}